# Generated by Django 4.2.11 on 2024-06-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_author_biography_alter_book_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_done',
            field=models.BooleanField(default=False),
        ),
    ]
